config/routes.rb
Rails.application.routes.draw do
  resources :rooms  do
    member do
      post :index
    end  
  end
  resources :meetings do 
    member do
      post :move
      post :resize
      post :new
    end 
  end

  root 'rooms#index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
    validates  :start_at, presence:true
    validates  :end_at  , presence:true    
    validates  :notes   , presence:true
    validates  :room_id , presence:true
    validate   :meeting_time_is_free
    validate   :meeting_time_is_valid
    belongs_to :room
    
    COLORS = ['#FF8080','#FFFF80','#B2FFB2','#B280B2','#80FFFF','#4D4DFF','#999999','#FF944D','#335C33','#855C33']

    def meeting_time_is_free        
          meetings = Meeting.where(:room_id => room_id)
          for meeting in meetings
              if end_at > meeting.start_at and end_at <= meeting.end_at
                  if room_id == meeting.room_id and not self == meeting
                    errors.add(:base, "There is already a meeting in the room at this time")
                  end
              end
              if start_at >= meeting.start_at and start_at < meeting.end_at
                  if room_id == meeting.room_id and not self == meeting
                   errors.add(:base, "There is already a meeting in the room at this time")
                  end 
              end
              if meeting.start_at >= start_at and meeting.start_at < end_at
                  if room_id == meeting.room_id and not self == meeting
                   errors.add(:base, "There is already a meeting in the room at this time")
                  end 
              end 
              if meeting.end_at > start_at and meeting.end_at <= end_at
                  if room_id == meeting.room_id and not self == meeting
                   errors.add(:base,"There is already a meeting in the room at this time")
                  end 
              end
          end  
    end

    def meeting_time_is_valid
        if start_at > end_at
            errors.add(:base,"Time is invalid, start time cannot be after meetime")
        end
        if start_at == end_at
            errors.add(:base,"Time is invalid, meeting must last at least 5 minutes")
        end
        if end_at < DateTime.now
            errors.add(:base, "Time is invalid, meeting cannot be scheduled in the past")
        end
    end

end

app/controllers/meetings_controller.rb
require 'icalendar'

class MeetingsController < ApplicationController
  
  before_action :set_meeting, only: [:show,:edit,:update,:destroy,:move,:resize]  
    
  respond_to :html, :xml, :json
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end
 
  # GET /meetings/1/edit
  def edit
  end
 
  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    
    respond_to do |format|
      if @meeting.save
        @room = Room.find(@meeting.room_id) 
        @meeting.color = Meeting::COLORS[@meeting.room_id % 10]
        @meeting.save
        format.html { redirect_to '/', notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created,location:'/'}
      else
        format.html { redirect_to '/'}
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      @room  = Room.find(@meeting.room_id)   
      if @meeting.update(meeting_params)    
        @meeting.color = Meeting::COLORS[params[:room_id] % 10]
        @meeting.save
        format.html { redirect_to @room, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @room}
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @room  = Room.find(@meeting.room_id) 
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to @room, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move 
    if @meeting
        @meeting.start_at= make_time(@meeting.start_at)
        @meeting.end_at  = make_time(@meeting.end_at)
        @meeting.save
        respond_with(@meeting)
    end
  end

  def resize
    if @meeting
        @meeting.end_at  = make_time(@meeting.end_at)
        @meeting.save
        respond_with(@meeting)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:notes, :start_at, :end_at,:room_id)
    end

    def make_time(event_time)
      time = params[:day_delta].to_i.days.from_now(event_time)
      time = params[:minute_delta].to_i.minutes.from_now(time)
      return time
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for @meeting, :html => { :id => 'meeting_form' } do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.notes %></td>
        <td><%= meeting.start_at %></td>
        <td><%= meeting.end_at %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notes:</strong>
  <%= @meeting.notes %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @meeting.start_at %>
</p>

<p>
  <strong>End Time:</strong>
  <%= @meeting.end_at %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %> |
<%= link_to 'Destroy', @meeting, method: :delete, data: { confirm: 'Are you sure?' } %>