config/routes.rb
Rails.application.routes.draw do
  resources :rooms  do
    member do
      post :index
    end  
  end
  resources :meetings do 
    member do
      post :move
      post :resize
      post :new
    end 
  end

  root 'rooms#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
    has_many :meetings
    validates :name, presence:true
    validates :name, uniqueness: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @meetings = Meeting.all
    respond_to do |format|
      format.html
      format.ics do
        cal = Icalendar::Calendar.new
        @meetings.each do |meeting|
            event = Icalendar::Event.new
            event.dtstart = meeting.start_at
            event.dtend   = meeting.end_at
            event.summary = meeting.notes
            event.description = meeting.room.name
            cal.add_event(event)
        end
        render :text => cal.to_ical
      end
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    set_room
    @rooms=  Room.all
    @meetings = Meeting.where(:room_id => @room.id)
    @meeting  = Meeting.new
    @ics_route = "/rooms/#{ @room.id.to_s }.ics"
    respond_to do |format|
      format.html
      format.ics do
        cal = Icalendar::Calendar.new
        @meetings.each do |meeting|
            event = Icalendar::Event.new
            event.dtstart = meeting.start_at
            event.dtend   = meeting.end_at
            event.summary = meeting.notes
            event.description = meeting.room.name
            cal.add_event(event)
        end
        render :text => cal.to_ical
      end
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def export
    
  end
  
  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name)
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%=pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>
      
      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_meetingform.html.erb
<%= form_for @meeting ||= Meeting.new, :html => { id: 'meeting_form' } do |f| %>
    
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  
  <div class="field">
    <%= f.label "room" %> <br>
    <%= f.select :room_id, Room.all.collect{|p| [ p.name, p.id ]}  %>
  </div>
  
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.datetime_select :end_at %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class= "center-block" style="width: 50%">
   <div class="btn-toolbar" style="width: 100%; text-align: center" >
    <% @rooms.each do |room| %>
        <a href="/rooms/<%=room.id%>" style="none" >
        <button type="button" class="btn btn-default" style="background-color:<%= Meeting::COLORS[room.id % 10] %>">
            <%= room.name%>
        </button>
        </a>
    <% end %>
     <%= link_to 'New Room', new_room_path %>
   </div> 
</div>

<br>
<br>

<%@meetings.each do |meeting| %>
    <% if meeting.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
 
            <ul>
                <% meeting.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>  
        </div>
    <%end%>
<%end%>

<br>    

<div class ="center-block" style="width: 80%">
    <div id='calendar'></div>
</div>

<div id="event_desc_dialog" class="dialog" style="display:none;">
</div>

<div id="create_meeting_dialog" class="dialog" style ="display:none;">
    <%= render 'meetingform' %>
</div>

<br>
<div class= "center-block" style="width: 50%">
   <div class="btn-toolbar" style="width: 100%; text-align: center" >
      <button type="button" class="btn btn-default" id='export'>
           <%= link_to 'Export', "/rooms.ics" %>
      </button>
   </div> 
</div>

<br>
<br>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class= "center-block" style="width: 50%">
    <div class="btn-toolbar" style="width: 100%; text-align: center" >
        <% @rooms.each do |room| %>
        <a href="/rooms/<%=room.id%>" style="none" >
         <% if @room.id == room.id %>
            <button type="button" class="btn btn-default" style="background-color:<%= Meeting::COLORS[room.id % 10] %>">
            <%= room.name%>
            </button>
        <% else %>
             <button type="button" class="btn btn-default" style="background-color:white">
            <%= room.name%>
            </button>
        <% end %>
        </a>
    <% end %>
 </div>
</div>

<br>
<br>

<div class ="center-block" style="width: 80%">
    <div 
        id='calendar_show'>
    </div>
</div>

<script>
    $(document).on('ready page:load',function() {
            $('#calendar_show').fullCalendar('removeEvents');
            
            <%@rooms.each do |aRoom| %>
                $('#calendar_show').fullCalendar('removeEventSource','/rooms/'+<%=aRoom.id%>+'.json');
            <%end%>

            $('#calendar_show').fullCalendar('addEventSource','/rooms/'+<%=@room.id%>+'.json' );
            $('#calendar_show').fullCalendar('refetchEvents'); 
    });
</script>

<div id="event_desc_dialog" class="dialog" style="display:none;"></div>
<div id="create_meeting_dialog" class="dialog" style ="display:none;">
      <%= render 'meetingform' %>
</div>

<br>
<div class= "center-block" style="width: 50%">
 <div class="btn-toolbar" style="width: 100%; text-align: center" >
  <button type="button" class="btn btn-default" id='export'>
    <%= link_to 'Export', @ics_route %>
  </button>
 </div> 
</div>

<br>
<br>